# Generated by Django 2.1 on 2018-08-16 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20180816_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notebook',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
