# Generated by Django 2.1 on 2018-08-17 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_auto_20180817_1322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='date_updated',
            new_name='date_modified',
        ),
    ]
