# Generated by Django 2.1 on 2019-01-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_auto_20180817_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='favorited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='sync_id',
            field=models.CharField(default='I need a sync id!', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='trashed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notebook',
            name='sync_id',
            field=models.CharField(default='I need a sync id!', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='sync_id',
            field=models.CharField(default='I need a sync id!', max_length=50),
            preserve_default=False,
        ),
    ]
