# Generated by Django 2.1 on 2019-01-15 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_auto_20190115_2004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='sync_id',
            new_name='sync_hash',
        ),
        migrations.RenameField(
            model_name='notebook',
            old_name='sync_id',
            new_name='sync_hash',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='sync_id',
            new_name='sync_hash',
        ),
    ]
