# Generated by Django 2.1 on 2019-01-15 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_auto_20190115_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='sync_hash',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='sync_hash',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='sync_hash',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
