# Generated by Django 2.1 on 2019-01-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_auto_20190115_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='row',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
