# Generated by Django 2.1 on 2019-01-15 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0012_notebook_row'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='notes.Notebook'),
        ),
    ]
