# Generated by Django 2.1.5 on 2019-01-17 17:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0013_auto_20190115_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='sync_hash',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='sync_hash',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='tag',
            name='sync_hash',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
