# Generated by Django 2.1.5 on 2019-01-17 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0014_auto_20190117_1701'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ('-date_modified',)},
        ),
        migrations.AlterModelOptions(
            name='notebook',
            options={'ordering': ('row',)},
        ),
        migrations.AlterField(
            model_name='notebook',
            name='row',
            field=models.IntegerField(blank=True, default=-255),
        ),
    ]
