# Generated by Django 2.1.5 on 2019-01-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0015_auto_20190117_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
