# Generated by Django 2.1.5 on 2019-01-18 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0016_auto_20190118_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='shared_with',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='shared_with',
        ),
    ]
