# Generated by Django 2.1.5 on 2019-01-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0017_auto_20190118_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_encrypted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notebook',
            name='is_encrypted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tag',
            name='is_encrypted',
            field=models.BooleanField(default=False),
        ),
    ]
