# Generated by Django 2.1.5 on 2019-01-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0018_auto_20190120_1709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('row',)},
        ),
        migrations.AddField(
            model_name='tag',
            name='row',
            field=models.IntegerField(blank=True, default=-255),
        ),
    ]
