# Generated by Django 2.1.5 on 2019-01-23 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0019_auto_20190122_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='is_encrypted',
            new_name='encrypted',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='is_public',
            new_name='public',
        ),
        migrations.RenameField(
            model_name='notebook',
            old_name='is_encrypted',
            new_name='encrypted',
        ),
        migrations.RenameField(
            model_name='notebook',
            old_name='is_public',
            new_name='public',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='is_encrypted',
            new_name='encrypted',
        ),
    ]
