# Generated by Django 2.1 on 2018-08-16 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_auto_20180816_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='note.Notebook'),
        ),
        migrations.AlterField(
            model_name='note',
            name='notebook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='note.Notebook'),
        ),
    ]
